# Generated by Django 6.0.3 on 2026-04-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timesheet",
            options={"ordering": ["employee", "week_number"]},
        ),
        migrations.AddField(
            model_name="timesheet",
            name="week_number",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="timesheet",
            unique_together={("employee", "week_number")},
        ),
        migrations.AddIndex(
            model_name="timesheet",
            index=models.Index(
                fields=["employee"], name="pages_times_employe_485b74_idx"
            ),
        ),
    ]
