# Generated by Django 6.0.3 on 2026-04-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_timesheet_options_timesheet_week_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="project_name",
            field=models.CharField(default="General", max_length=100),
        ),
    ]
