# Generated by Django 6.0.4 on 2026-05-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_timesheet_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="task_description",
            field=models.CharField(default="General Admin", max_length=100),
        ),
    ]
